version: "3.9"

services:
  recepcao-enfermagem:
    build:
      context: .
      dockerfile: Dockerfile-python-gunicorn
    restart: unless-stopped
    ports:
      - "8010:80"
    environment:
      - DJANGO_SETTINGS_MODULE=hospital.settings
    volumes:
      - static_volume:/recepcao-enfermagem-django/static
      - media_volume:/recepcao-enfermagem-django/media
    networks:
      - recepcao-network

volumes:
  static_volume:
  media_volume:

networks:
  recepcao-network:
    driver: bridge