# Generated by Django 4.1.7 on 2023-02-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionario", "0003_alter_questionario01_atualizado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionario01",
            name="atualizado",
            field=models.DateField(default="2023-02-21"),
        ),
        migrations.AlterField(
            model_name="questionario01",
            name="data_cadastro",
            field=models.DateField(default="2023-02-21"),
        ),
        migrations.AlterField(
            model_name="questionario01",
            name="data_cirurgia",
            field=models.DateField(default="2023-02-21"),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="atualizado",
            field=models.DateField(default="2023-02-21"),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="data_cadastro",
            field=models.DateField(default="2023-02-21"),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="realizou_hemodialise_se_sim_02",
            field=models.DateField(default="2023-02-21"),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="realizou_quimeoterapia_se_sim_02",
            field=models.DateField(default="2023-02-21"),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="realizou_radioterapia_se_sim_02",
            field=models.DateField(default="2023-02-21"),
        ),
    ]
