# Generated by Django 4.1.7 on 2023-02-22 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("questionario", "0005_alter_questionario01_atualizado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionario0101",
            name="jejum_se_sim",
            field=models.TimeField(default="12:47"),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="triconomia_realizada_se_sim_01",
            field=models.TimeField(default="12:47"),
        ),
        migrations.AlterField(
            model_name="questionario0102",
            name="antibiotico_profilatico_a_u_m_se_sim_01",
            field=models.TimeField(default="12:47", max_length=1),
        ),
        migrations.AlterField(
            model_name="questionario0102",
            name="hora_incisao_c",
            field=models.TimeField(default="12:47"),
        ),
        migrations.CreateModel(
            name="Questionario0103",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instrumentais_antes", models.PositiveIntegerField(default=0)),
                ("compressas_antes", models.PositiveIntegerField(default=0)),
                ("agulhas_antes", models.PositiveIntegerField(default=0)),
                ("lamina_bisturi", models.PositiveIntegerField(default=0)),
                ("instrumentais_depois", models.PositiveIntegerField(default=0)),
                ("compressas_depois", models.PositiveIntegerField(default=0)),
                ("agulhas_depois", models.PositiveIntegerField(default=0)),
                ("cirurgia_realizada", models.CharField(default="", max_length=50)),
                (
                    "registro_completo_p_p_l_p",
                    models.CharField(default="", max_length=1),
                ),
                ("houve_algum_p_m_e_i", models.CharField(default="", max_length=1)),
                ("peca_patologica", models.CharField(default="", max_length=1)),
                ("amostra_cultura", models.CharField(default="", max_length=1)),
                ("citologia_oncotica", models.CharField(default="", max_length=1)),
                ("amostra_lcr", models.CharField(default="", max_length=1)),
                ("alta_confirmada", models.CharField(default="", max_length=15)),
                ("observacoes", models.TextField(default="", max_length=200)),
                ("cirurgiao", models.CharField(default="", max_length=50)),
                ("anestesista", models.CharField(default="", max_length=50)),
                ("enfermeiro", models.CharField(default="", max_length=50)),
                ("circulante", models.CharField(default="", max_length=50)),
                ("data_cadastro", models.DateField(default="2023-02-22")),
                ("atualizado", models.DateField(default="2023-02-22")),
                (
                    "cirurgia_segura",
                    models.OneToOneField(
                        default="",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="questionario.questionario01",
                    ),
                ),
            ],
        ),
    ]
