# Generated by Django 4.1.7 on 2023-02-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionario", "0006_alter_questionario0101_jejum_se_sim_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="questionario0103",
            old_name="lamina_bisturi",
            new_name="lamina_bisturi_antes",
        ),
        migrations.AddField(
            model_name="questionario0103",
            name="lamina_bisturi_depois",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="jejum_se_sim",
            field=models.TimeField(default="12:59"),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="triconomia_realizada_se_sim_01",
            field=models.TimeField(default="12:59"),
        ),
        migrations.AlterField(
            model_name="questionario0102",
            name="antibiotico_profilatico_a_u_m_se_sim_01",
            field=models.TimeField(default="12:59", max_length=1),
        ),
        migrations.AlterField(
            model_name="questionario0102",
            name="hora_incisao_c",
            field=models.TimeField(default="12:59"),
        ),
    ]
