# Generated by Django 4.1.7 on 2023-02-24 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0005_alter_colaborador_atualizado_and_more"),
        (
            "questionario",
            "0007_rename_lamina_bisturi_questionario0103_lamina_bisturi_antes_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionario01",
            name="atualizado",
            field=models.DateField(default="2023-02-24"),
        ),
        migrations.AlterField(
            model_name="questionario01",
            name="data_cadastro",
            field=models.DateField(default="2023-02-24"),
        ),
        migrations.AlterField(
            model_name="questionario01",
            name="data_cirurgia",
            field=models.DateField(default="2023-02-24"),
        ),
        migrations.AlterField(
            model_name="questionario01",
            name="modalidade",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="alergia_conhecida",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="atualizado",
            field=models.DateField(default="2023-02-24"),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="data_cadastro",
            field=models.DateField(default="2023-02-24"),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="exames_laborat_i_d",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="jejum",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="jejum_se_sim",
            field=models.TimeField(default="10:54"),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="possui_dispositivos",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="possui_dispositivos_se_sim",
            field=models.CharField(default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="procedimento_confirmado",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="prontuario_completo",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="prontuario_completo_se_nao",
            field=models.CharField(default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="pulseira_identificacao",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="realizou_hemodialise",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="realizou_hemodialise_se_sim_02",
            field=models.DateField(default="2023-02-24"),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="realizou_quimeoterapia",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="realizou_quimeoterapia_se_sim_02",
            field=models.DateField(default="2023-02-24"),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="realizou_radioterapia",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="realizou_radioterapia_se_sim_02",
            field=models.DateField(default="2023-02-24"),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="realizou_transplante_o",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="resserva_CTI",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="resserva_hemoderivados",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="risco_perda_s",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="sitio_cirurgico_d",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="tempo_previsto_cirurgia",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="termo_consentimento_c_a",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="triconomia_realizada",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="triconomia_realizada_se_sim_01",
            field=models.TimeField(default="10:54"),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="triconomia_realizada_se_sim_02",
            field=models.CharField(default="", max_length=31),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="verificacao_anestesica_m_v_m_e_a",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="vias_aereas_d_r_a",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0102",
            name="antes_assepsia_c_o",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0102",
            name="antes_assepsia_c_o_se_sim",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0102",
            name="antibiotico_profilatico_a_u_m",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0102",
            name="antibiotico_profilatico_a_u_m_se_sim_01",
            field=models.TimeField(default="10:54", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0102",
            name="atualizado",
            field=models.DateField(default="2023-02-24"),
        ),
        migrations.AlterField(
            model_name="questionario0102",
            name="data_cadastro",
            field=models.DateField(default="2023-02-24"),
        ),
        migrations.AlterField(
            model_name="questionario0102",
            name="data_vencimento",
            field=models.DateField(default="2023-02-24"),
        ),
        migrations.AlterField(
            model_name="questionario0102",
            name="fita_indicador_q_m",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0102",
            name="hora_incisao_c",
            field=models.TimeField(default="10:54"),
        ),
        migrations.AlterField(
            model_name="questionario0102",
            name="integrador_material",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0102",
            name="lateralidade",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0102",
            name="materiais_instumentais_c_d",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0102",
            name="nome_paciente",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0102",
            name="placa_bisturi_p",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0102",
            name="procedimento",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0102",
            name="sitio_cirurgico",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0102",
            name="todos_membros_e_e_p",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0103",
            name="alta_confirmada",
            field=models.CharField(default="", max_length=35),
        ),
        migrations.AlterField(
            model_name="questionario0103",
            name="amostra_cultura",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0103",
            name="amostra_lcr",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0103",
            name="atualizado",
            field=models.DateField(default="2023-02-24"),
        ),
        migrations.AlterField(
            model_name="questionario0103",
            name="citologia_oncotica",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0103",
            name="data_cadastro",
            field=models.DateField(default="2023-02-24"),
        ),
        migrations.AlterField(
            model_name="questionario0103",
            name="houve_algum_p_m_e_i",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0103",
            name="peca_patologica",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0103",
            name="registro_completo_p_p_l_p",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.CreateModel(
            name="Questionario02",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnostico_cid", models.CharField(default="", max_length=50)),
                (
                    "sinais_sintomas_fisicos",
                    models.CharField(default="", max_length=50),
                ),
                ("tem_acompanhemento", models.CharField(default="", max_length=50)),
                ("tratamento_realizado", models.CharField(default="", max_length=20)),
                (
                    "tratamento_realizado_out",
                    models.CharField(default="", max_length=50),
                ),
                ("nivel_autonimia", models.CharField(default="", max_length=50)),
                ("historia_progressa", models.CharField(default="", max_length=50)),
                ("alergias", models.CharField(default="", max_length=50)),
                ("alergias_out", models.CharField(default="", max_length=50)),
                (
                    "possiveis_sinais_sintomas_rt",
                    models.CharField(default="", max_length=50),
                ),
                ("nutricao", models.CharField(default="", max_length=300)),
                (
                    "quantas_refeicoes_realizadas",
                    models.PositiveIntegerField(default=""),
                ),
                (
                    "possui_alguma_dessas_d",
                    models.CharField(default="", max_length=300),
                ),
                ("alteracao_paladar", models.CharField(default="", max_length=3)),
                (
                    "alteracao_paladar_se_sim",
                    models.CharField(default="", max_length=300),
                ),
                (
                    "qual_ingesta_hidrica_d",
                    models.CharField(default="", max_length=300),
                ),
                ("apresenta", models.CharField(default="", max_length=300)),
                ("apresenta_mucosite", models.CharField(default="", max_length=300)),
                (
                    "apresenta_mucosite_se_sim",
                    models.CharField(default="", max_length=300),
                ),
                ("data_cadastro", models.DateField(default="2022-01-01")),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuario.paciente",
                    ),
                ),
            ],
        ),
    ]
