# Generated by Django 4.1.7 on 2023-02-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionario", "0008_alter_questionario01_atualizado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionario0101",
            name="jejum_se_sim",
            field=models.TimeField(default="11:20"),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="triconomia_realizada_se_sim_01",
            field=models.TimeField(default="11:20"),
        ),
        migrations.AlterField(
            model_name="questionario0102",
            name="antes_assepsia_c_o_se_sim",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="questionario0102",
            name="antibiotico_profilatico_a_u_m_se_sim_01",
            field=models.TimeField(default="11:20", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0102",
            name="hora_incisao_c",
            field=models.TimeField(default="11:20"),
        ),
    ]
