# Generated by Django 4.1.7 on 2023-03-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "questionario",
            "0010_rename_alteracao_paladar_se_sim_questionario02_alteracao_paladar_se_sim_01_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="questionario02",
            old_name="alteracao_paladar_se_sim_01",
            new_name="alteracao_paladar_se_sim",
        ),
        migrations.RenameField(
            model_name="questionario02",
            old_name="apresenta_mucosite_se_sim_01",
            new_name="apresenta_mucosite_se_sim",
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="jejum_se_sim",
            field=models.TimeField(default="11:8"),
        ),
        migrations.AlterField(
            model_name="questionario0101",
            name="triconomia_realizada_se_sim_01",
            field=models.TimeField(default="11:8"),
        ),
        migrations.AlterField(
            model_name="questionario0102",
            name="antibiotico_profilatico_a_u_m_se_sim_01",
            field=models.TimeField(default="11:8", max_length=3),
        ),
        migrations.AlterField(
            model_name="questionario0102",
            name="hora_incisao_c",
            field=models.TimeField(default="11:8"),
        ),
    ]
