# Generated by Django 4.1.7 on 2023-03-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('questionario', '0014_alter_questionario01_atualizado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionario0102',
            name='registro_completo_p_r_l_p',
        ),
        migrations.AlterField(
            model_name='questionario01',
            name='atualizado',
            field=models.DateField(default='2023-03-09'),
        ),
        migrations.AlterField(
            model_name='questionario01',
            name='data_cadastro',
            field=models.DateField(default='2023-03-09'),
        ),
        migrations.AlterField(
            model_name='questionario01',
            name='data_cirurgia',
            field=models.DateField(default='2023-03-09'),
        ),
        migrations.AlterField(
            model_name='questionario0101',
            name='atualizado',
            field=models.DateField(default='2023-03-09'),
        ),
        migrations.AlterField(
            model_name='questionario0101',
            name='data_cadastro',
            field=models.DateField(default='2023-03-09'),
        ),
        migrations.AlterField(
            model_name='questionario0101',
            name='jejum_se_sim',
            field=models.TimeField(default='10:11'),
        ),
        migrations.AlterField(
            model_name='questionario0101',
            name='realizou_hemodialise_se_sim_02',
            field=models.DateField(default='2023-03-09'),
        ),
        migrations.AlterField(
            model_name='questionario0101',
            name='realizou_quimeoterapia_se_sim_02',
            field=models.DateField(default='2023-03-09'),
        ),
        migrations.AlterField(
            model_name='questionario0101',
            name='realizou_radioterapia_se_sim_02',
            field=models.DateField(default='2023-03-09'),
        ),
        migrations.AlterField(
            model_name='questionario0101',
            name='triconomia_realizada_se_sim_01',
            field=models.TimeField(default='10:11'),
        ),
        migrations.AlterField(
            model_name='questionario0102',
            name='antibiotico_profilatico_a_u_m_se_sim_01',
            field=models.TimeField(default='10:11', max_length=3),
        ),
        migrations.AlterField(
            model_name='questionario0102',
            name='atualizado',
            field=models.DateField(default='2023-03-09'),
        ),
        migrations.AlterField(
            model_name='questionario0102',
            name='data_cadastro',
            field=models.DateField(default='2023-03-09'),
        ),
        migrations.AlterField(
            model_name='questionario0102',
            name='data_vencimento',
            field=models.DateField(default='2023-03-09'),
        ),
        migrations.AlterField(
            model_name='questionario0102',
            name='hora_incisao_c',
            field=models.TimeField(default='10:11'),
        ),
        migrations.AlterField(
            model_name='questionario0103',
            name='data_cadastro',
            field=models.DateField(default='2023-03-09'),
        ),
        migrations.AlterField(
            model_name='questionario02',
            name='atualizado',
            field=models.DateField(default='2023-03-09'),
        ),
        migrations.AlterField(
            model_name='questionario02',
            name='data_cadastro',
            field=models.DateField(default='2023-03-09'),
        ),
        migrations.AlterField(
            model_name='questionario02',
            name='tratamento_realizado',
            field=models.CharField(default='', max_length=50),
        ),
    ]
