# Generated by Django 4.1.7 on 2023-03-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('questionario', '0018_alter_questionario0101_jejum_se_sim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario0101',
            name='jejum_se_sim',
            field=models.TimeField(default='15:0'),
        ),
        migrations.AlterField(
            model_name='questionario0101',
            name='triconomia_realizada_se_sim_01',
            field=models.TimeField(default='15:0'),
        ),
        migrations.AlterField(
            model_name='questionario0102',
            name='antibiotico_profilatico_a_u_m_se_sim_01',
            field=models.TimeField(default='15:0', max_length=3),
        ),
        migrations.AlterField(
            model_name='questionario0102',
            name='hora_incisao_c',
            field=models.TimeField(default='15:0'),
        ),
        migrations.AlterField(
            model_name='questionario02',
            name='apresenta',
            field=models.CharField(
                choices=[('Desidratação', 'Desidratação'), ('Sialorréia', 'Sialorréia'), ('Desnutrição', 'Desnutrição'),
                         ('Astenia', 'Astenia')], default='', max_length=300),
        ),
    ]
