# Generated by Django 4.1.7 on 2023-03-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0022_alter_questionario0101_jejum_se_sim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario0101',
            name='jejum_se_sim',
            field=models.TimeField(default='18:31'),
        ),
        migrations.AlterField(
            model_name='questionario0101',
            name='triconomia_realizada_se_sim_01',
            field=models.TimeField(default='18:31'),
        ),
        migrations.AlterField(
            model_name='questionario0102',
            name='antibiotico_profilatico_a_u_m_se_sim_01',
            field=models.TimeField(default='18:31', max_length=3),
        ),
        migrations.AlterField(
            model_name='questionario0102',
            name='hora_incisao_c',
            field=models.TimeField(default='18:31'),
        ),
        migrations.AlterField(
            model_name='questionario02',
            name='alergias',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='questionario02',
            name='apresenta',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='questionario02',
            name='historia_progressa',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='questionario02',
            name='nivel_autonimia',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='questionario02',
            name='nutricao',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='questionario02',
            name='possiveis_sinais_sintomas_rt',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='questionario02',
            name='possui_alguma_dessas_d',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='questionario02',
            name='qual_ingesta_hidrica_d',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='questionario02',
            name='tratamento_realizado',
            field=models.CharField(default='', max_length=50),
        ),
    ]
