# Generated by Django 4.1.7 on 2023-03-13 12:33

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0029_alter_questionario0101_jejum_se_sim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario0101',
            name='jejum_se_sim',
            field=models.TimeField(default='9:33'),
        ),
        migrations.AlterField(
            model_name='questionario0101',
            name='triconomia_realizada_se_sim_01',
            field=models.TimeField(default='9:33'),
        ),
        migrations.AlterField(
            model_name='questionario0102',
            name='antibiotico_profilatico_a_u_m_se_sim_01',
            field=models.TimeField(default='9:33', max_length=3),
        ),
        migrations.AlterField(
            model_name='questionario0102',
            name='hora_incisao_c',
            field=models.TimeField(default='9:33'),
        ),
        migrations.AlterField(
            model_name='questionario02',
            name='qual_ingesta_hidrica_d',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Água', 'Água'), ('Sucos Naturais', 'Sucos Naturais'), ('Sucos Industrializados', 'Sucos Industrializados'), ('Refrigerantes', 'Refrigerantes'), ('Bebidas', 'Bebidas'), ('Alcoólicas', 'Alcoólicas'), ('Água de Coco', 'Água de Coco')], default='', max_length=300),
        ),
    ]
