# Generated by Django 4.1.7 on 2023-03-13 15:46

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0030_alter_questionario0101_jejum_se_sim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario0101',
            name='jejum_se_sim',
            field=models.TimeField(default='12:46'),
        ),
        migrations.AlterField(
            model_name='questionario0101',
            name='triconomia_realizada_se_sim_01',
            field=models.TimeField(default='12:46'),
        ),
        migrations.AlterField(
            model_name='questionario0102',
            name='antibiotico_profilatico_a_u_m_se_sim_01',
            field=models.TimeField(default='12:46', max_length=3),
        ),
        migrations.AlterField(
            model_name='questionario0102',
            name='hora_incisao_c',
            field=models.TimeField(default='12:46'),
        ),
        migrations.AlterField(
            model_name='questionario02',
            name='alergias',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Medicamentosa', 'Medicamentosa'), ('Alimentar', 'Alimentar'), ('Respiratória', 'Respiratória'), ('Cutânea', 'Cutânea'), ('Out', 'Outras')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='questionario02',
            name='nutricao',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Oral', 'Oral'), ('GTT', 'GTT'), ('SNE', 'SNE'), ('CNG', 'CNG')], default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='questionario02',
            name='possiveis_sinais_sintomas_rt',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Diarreia', 'Diarreia'), ('Constipação', 'Constipação'), ('Tosse', 'Tosse'), ('Dispnéia', 'Dispnéia'), ('Palpitação', 'Palpitação'), ('Prurido', 'Prurido'), ('Náusea', 'Náusea'), ('Êmese', 'Êmese'), ('Astenia', 'Astenia'), ('Inapetência', 'Inapetência'), ('Anorexia', 'Anorexia'), ('Edema', 'Edema'), ('Infecção', 'Infecção'), ('Síncope', 'Síncope'), ('Alteração Motora', 'Alteração Motora'), ('Sangramento', 'Sangramento'), ('Alteração Circulatória', 'Alteração Circulatória')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='questionario02',
            name='tratamento_realizado',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Quimioterapia', 'Quimioterapia'), ('Radioterapia', 'Radioterapia'), ('Cirurgia', 'Cirurgia'), ('Out', 'Outro')], default='', max_length=50),
        ),
    ]
