# Generated by Django 4.1.7 on 2023-03-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0033_rename_novel_consciencia_questionario02_nivel_consciencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario0101',
            name='jejum_se_sim',
            field=models.TimeField(default='14:11'),
        ),
        migrations.AlterField(
            model_name='questionario0101',
            name='triconomia_realizada_se_sim_01',
            field=models.TimeField(default='14:11'),
        ),
        migrations.AlterField(
            model_name='questionario0102',
            name='antibiotico_profilatico_a_u_m_se_sim_01',
            field=models.TimeField(default='14:11', max_length=3),
        ),
        migrations.AlterField(
            model_name='questionario0102',
            name='hora_incisao_c',
            field=models.TimeField(default='14:11'),
        ),
    ]
