# Generated by Django 4.1.6 on 2023-02-17 20:08

import cpf_field.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cpf",
                    cpf_field.models.CPFField(default="", max_length=14, unique=True),
                ),
                ("nome_completo", models.CharField(default="", max_length=100)),
                ("data_nascimento", models.DateField(verbose_name="2023-02-17")),
                ("idade", models.IntegerField(default=0)),
                ("reside_em", models.CharField(default="", max_length=100)),
                ("telefone", models.CharField(default="", max_length=20)),
                ("nome_mae", models.CharField(default="", max_length=100)),
                ("nome_pai", models.CharField(default="", max_length=100)),
                ("data_cadastro", models.DateField(verbose_name="2023-02-17")),
                ("atualizado", models.DateField(verbose_name="2023-02-17")),
            ],
        ),
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prontuario",
                    models.CharField(default="", max_length=50, unique=True),
                ),
                ("data_cadastro", models.DateField(verbose_name="2023-02-17")),
                ("atualizado", models.DateField(verbose_name="2023-02-17")),
                (
                    "usuario",
                    models.OneToOneField(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuario.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Colaborador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("funcao", models.CharField(default="", max_length=20)),
                ("carteria_trabalho", models.CharField(default="", max_length=50)),
                ("data_cadastro", models.DateField(verbose_name="2023-02-17")),
                ("atualizado", models.DateField(verbose_name="2023-02-17")),
                (
                    "usuario",
                    models.OneToOneField(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuario.usuario",
                    ),
                ),
            ],
        ),
    ]
