# Generated by Django 4.1.7 on 2023-02-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0004_alter_colaborador_atualizado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colaborador",
            name="atualizado",
            field=models.DateField(verbose_name="2023-02-24"),
        ),
        migrations.AlterField(
            model_name="colaborador",
            name="data_cadastro",
            field=models.DateField(verbose_name="2023-02-24"),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="atualizado",
            field=models.DateField(default="date"),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="data_cadastro",
            field=models.DateField(default="date"),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="atualizado",
            field=models.DateField(default="date"),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="data_cadastro",
            field=models.DateField(default="date"),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="data_nascimento",
            field=models.DateField(verbose_name="2023-02-24"),
        ),
    ]
