# Generated by Django 4.1.7 on 2023-03-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_alter_colaborador_atualizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='reg',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='atualizado',
            field=models.DateField(verbose_name='2023-03-27'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='data_cadastro',
            field=models.DateField(verbose_name='2023-03-27'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(verbose_name='2023-03-27'),
        ),
    ]
